version: 0.8.0.1
github: tek/polysemy-conc
license: BSD-2-Clause-Patent
license-file: LICENSE
author: "Torsten Schmits"
maintainer: "haskell@tryp.io"
copyright: "2021 Torsten Schmits"
category: Concurrency
build-type: Simple
extra-source-files:
  - readme.md
  - changelog.md
